const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');

const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;
const DATA_DIR = process.env.DATA_DIR || path.join(ROOT, 'data');
fs.mkdirSync(DATA_DIR, { recursive: true });
const db = new DatabaseSync(path.join(DATA_DIR, 'campus-events.db'));
db.exec(`PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password TEXT NOT NULL, salt TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'student', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY, title TEXT NOT NULL, category TEXT NOT NULL, description TEXT NOT NULL, date TEXT NOT NULL, time TEXT NOT NULL, venue TEXT NOT NULL, organizer TEXT NOT NULL, capacity INTEGER NOT NULL CHECK(capacity > 0), image TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'upcoming', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS registrations(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE, registered_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id,event_id));
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL);`);

const count = db.prepare('SELECT count(*) AS n FROM events').get().n;
if (!count) {
  const insert = db.prepare('INSERT INTO events(title,category,description,date,time,venue,organizer,capacity,image) VALUES(?,?,?,?,?,?,?,?,?)');
  [
    ['Designing Tomorrow','Design','A hands-on design sprint where ideas become prototypes. Work in teams with mentors from the campus design community and share your final concept.', '2026-10-18','10:00 AM','Innovation Lab · Block B','Design Society',80,'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1000&q=85'],
    ['Indie Sound Sessions','Music','An evening of live sets from student artists, open-mic performances and good company. Bring a friend and discover your next favorite band.', '2026-10-20','5:30 PM','Open Air Theatre','Music Club',250,'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1000&q=85'],
    ['Build for Good Hackathon','Technology','A day-long buildathon centered on tools for a more accessible and sustainable world. Teams of 2–4 welcome. Laptops and lunch provided.', '2026-10-24','9:00 AM','Tech Park · Level 2','ACM Student Chapter',120,'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1000&q=85'],
    ['Courtside: Campus Cup','Sports','Cheer on your house at the annual campus basketball cup. Expect close games, a halftime challenge and refreshments courtside.', '2026-10-26','3:00 PM','University Sports Complex','Athletics Council',180,'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1000&q=85'],
    ['The Future of AI','Talks','A candid conversation with researchers and builders about practical AI, responsible innovation and the questions worth asking next.', '2026-10-29','4:00 PM','Mini Auditorium · Main Block','ACM Student Chapter',90,'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1000&q=85'],
    ['Moonlight Market','Community','A night market made by students: small-batch crafts, thrift finds, local food and a little live music. Every purchase supports student makers.', '2026-11-02','6:00 PM','Central Courtyard','Student Affairs',300,'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1000&q=85']
  ].forEach(e => insert.run(...e));
}

const mime = { '.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml' };
const statements = {
  events: db.prepare(`SELECT e.*, COUNT(r.id) AS registered, e.capacity-COUNT(r.id) AS seats_left FROM events e LEFT JOIN registrations r ON r.event_id=e.id WHERE e.status='upcoming' GROUP BY e.id ORDER BY e.date,e.time`),
  event: db.prepare(`SELECT e.*, COUNT(r.id) AS registered, e.capacity-COUNT(r.id) AS seats_left FROM events e LEFT JOIN registrations r ON r.event_id=e.id WHERE e.id=? GROUP BY e.id`)
};
function send(res, status, data, headers={}) { res.writeHead(status, {'content-type':'application/json; charset=utf-8',...headers}); res.end(JSON.stringify(data)); }
function cookie(req,name) { return (req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1); }
function currentUser(req) { const token=cookie(req,'campus_session'); if(!token)return null; const row=db.prepare('SELECT u.id,u.name,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?').get(token,Date.now()); return row||null; }
async function body(req) { let raw=''; for await(const chunk of req) { raw+=chunk; if(raw.length>1_000_000) throw Error('Request too large'); } try{return raw?JSON.parse(raw):{};}catch{return null;} }
function hash(password,salt=crypto.randomBytes(16).toString('hex')) { return {salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}; }
function cleanEvent(row) { return row; }
function route(req,res) { (async()=>{
  const url=new URL(req.url,'http://localhost'); const p=url.pathname; const method=req.method;
  if(method==='GET' && p==='/api/events') return send(res,200,statements.events.all().map(cleanEvent));
  if(method==='GET' && /^\/api\/events\/\d+$/.test(p)){const event=statements.event.get(Number(p.split('/').pop())); return event?send(res,200,event):send(res,404,{error:'Event not found'});}
  if(method==='GET' && p==='/api/me'){const user=currentUser(req); if(!user)return send(res,200,{user:null}); const registrations=db.prepare('SELECT e.*,r.registered_at FROM registrations r JOIN events e ON e.id=r.event_id WHERE r.user_id=? ORDER BY e.date').all(user.id); return send(res,200,{user,registrations});}
  if(method==='POST' && (p==='/api/register'||p==='/api/login')) { const data=await body(req); if(!data)return send(res,400,{error:'Please send valid JSON.'}); let user;
    if(p.endsWith('register')) { if(!data.name?.trim()||!/^\S+@\S+\.\S+$/.test(data.email||'')||(data.password||'').length<8)return send(res,400,{error:'Enter your name, a valid email and a password with at least 8 characters.'}); const creds=hash(data.password); try {const info=db.prepare('INSERT INTO users(name,email,password,salt) VALUES(?,?,?,?)').run(data.name.trim(),data.email.toLowerCase(),creds.hash,creds.salt); user={id:Number(info.lastInsertRowid),name:data.name.trim(),email:data.email.toLowerCase(),role:'student'};} catch{return send(res,409,{error:'An account with this email already exists.'});} }
    else {const found=db.prepare('SELECT * FROM users WHERE email=?').get((data.email||'').toLowerCase()); if(!found||hash(data.password||'',found.salt).hash!==found.password)return send(res,401,{error:'Email or password is incorrect.'}); user={id:found.id,name:found.name,email:found.email,role:found.role};}
    const token=crypto.randomBytes(32).toString('hex'); db.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)').run(token,user.id,Date.now()+7*86400000); return send(res,200,{user},{'set-cookie':`campus_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`}); }
  if(method==='POST' && p==='/api/logout'){const token=cookie(req,'campus_session');if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(token);return send(res,200,{ok:true},{'set-cookie':'campus_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});}
  if(method==='POST' && /^\/api\/events\/\d+\/register$/.test(p)){const user=currentUser(req);if(!user)return send(res,401,{error:'Sign in to reserve your place.'});const id=Number(p.split('/')[3]);const event=db.prepare('SELECT * FROM events WHERE id=? AND status=?').get(id,'upcoming');if(!event)return send(res,404,{error:'This event is no longer available.'});let result;db.exec('BEGIN IMMEDIATE');try{if(db.prepare('SELECT 1 FROM registrations WHERE user_id=? AND event_id=?').get(user.id,id))result='duplicate';else{const n=db.prepare('SELECT count(*) AS n FROM registrations WHERE event_id=?').get(id).n;if(n>=event.capacity)result='full';else{db.prepare('INSERT INTO registrations(user_id,event_id) VALUES(?,?)').run(user.id,id);result='ok';}}db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}if(result==='duplicate')return send(res,409,{error:'You are already registered for this event.'});if(result==='full')return send(res,409,{error:'This event is full. Keep an eye out for the next one.'});return send(res,201,{message:'You’re on the list. See you there!'});}
  if(method==='DELETE' && /^\/api\/events\/\d+\/register$/.test(p)){const user=currentUser(req);if(!user)return send(res,401,{error:'Sign in first.'});const result=db.prepare('DELETE FROM registrations WHERE user_id=? AND event_id=?').run(user.id,Number(p.split('/')[3]));return result.changes?send(res,200,{message:'Your place has been released.'}):send(res,404,{error:'No registration found to cancel.'});}
  if(p==='/api/admin/events'&&method==='POST'||/^\/api\/admin\/events\/\d+$/.test(p)){const user=currentUser(req);if(!user||user.role!=='organizer')return send(res,403,{error:'Organizer access required.'});if(method==='POST'&&p==='/api/admin/events'){const d=await body(req);if(!d?.title||!d.date||!Number.isInteger(+d.capacity)||+d.capacity<1)return send(res,400,{error:'Title, date and a positive capacity are required.'});const result=db.prepare('INSERT INTO events(title,category,description,date,time,venue,organizer,capacity,image) VALUES(?,?,?,?,?,?,?,?,?)').run(d.title,d.category||'Community',d.description||'',d.date,d.time||'12:00 PM',d.venue||'Campus',user.name,+d.capacity,d.image||'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1000&q=85');return send(res,201,{event:statements.event.get(Number(result.lastInsertRowid))});}const id=Number(p.split('/').pop());if(method==='PUT'){const d=await body(req);db.prepare('UPDATE events SET title=?,category=?,description=?,date=?,time=?,venue=?,capacity=?,status=? WHERE id=?').run(d.title,d.category,d.description,d.date,d.time,d.venue,Math.max(1,+d.capacity||1),d.status||'upcoming',id);return send(res,200,{event:statements.event.get(id)});}if(method==='DELETE'){db.prepare('DELETE FROM events WHERE id=?').run(id);return send(res,200,{ok:true});}}
  if(method==='POST'&&p==='/api/admin/seed-organizer'){if(!process.env.ORGANIZER_EMAIL||!process.env.ORGANIZER_PASSWORD)return send(res,404,{error:'Set ORGANIZER_EMAIL and ORGANIZER_PASSWORD to enable organizer setup.'});const d=await body(req);if(d?.key!==process.env.ORGANIZER_PASSWORD)return send(res,403,{error:'Invalid setup key.'});const email=process.env.ORGANIZER_EMAIL.toLowerCase();if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return send(res,409,{error:'Organizer account already exists.'});const c=hash(process.env.ORGANIZER_PASSWORD);db.prepare("INSERT INTO users(name,email,password,salt,role) VALUES(?,?,?,?,'organizer')").run('Event Organizer',email,c.hash,c.salt);return send(res,201,{message:'Organizer created. Sign in with the configured email and password.'});}
  return send(res,404,{error:'Not found'});
 })().catch(err=>{console.error(err);if(!res.headersSent)send(res,500,{error:'Something went wrong. Please try again.'});}); }

http.createServer((req,res)=>{if(req.url.startsWith('/api/'))return route(req,res);let target=path.join(ROOT,'public',decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(target.endsWith(path.sep))target+='index.html';if(!target.startsWith(path.join(ROOT,'public')))target=path.join(ROOT,'public','index.html');fs.readFile(target,(err,content)=>{if(err){fs.readFile(path.join(ROOT,'public','index.html'),(e,fallback)=>{if(e){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'content-type':mime['.html']});res.end(fallback);});return;}res.writeHead(200,{'content-type':mime[path.extname(target)]||'application/octet-stream','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'});res.end(content);});}).listen(PORT,()=>console.log(`Campus events running at http://localhost:${PORT}`));
